import { afterEach, beforeEach, describe, expect, it } from "bun:test";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { readProviderFromModelsYml } from "../src/models-yml";

describe("readProviderFromModelsYml", () => {
	let tempDir: string;
	let modelsPath: string;

	beforeEach(() => {
		tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "pi-models-yml-"));
		modelsPath = path.join(tempDir, "models.yml");
	});

	afterEach(() => {
		fs.rmSync(tempDir, { recursive: true, force: true });
	});

	function write(yaml: string): void {
		fs.writeFileSync(modelsPath, yaml);
	}

	it("returns null when the file does not exist", () => {
		expect(readProviderFromModelsYml("anthropic", modelsPath)).toBeNull();
	});

	it("parses a typical auto-generated block with env var apiKey", () => {
		write(
			[
				"# Auto-generated by xcsh",
				"configVersion: 2",
				"providers:",
				"  anthropic:",
				'    baseUrl: "https://proxy.example.com/anthropic"',
				"    apiKey: LITELLM_API_KEY",
				"  litellm:",
				'    baseUrl: "https://proxy.example.com/v1"',
				"    apiKey: LITELLM_API_KEY",
				"",
			].join("\n"),
		);

		const block = readProviderFromModelsYml("anthropic", modelsPath);
		expect(block?.baseUrl).toBe("https://proxy.example.com/anthropic");
		expect(block?.apiKey).toEqual({ kind: "envVar", name: "LITELLM_API_KEY" });
	});

	it("parses a double-quoted literal apiKey and decodes escapes", () => {
		write(
			[
				"providers:",
				"  anthropic:",
				'    baseUrl: "https://proxy.example.com/anthropic"',
				'    apiKey: "sk-\\"escaped\\"-\\\\key"',
				"",
			].join("\n"),
		);

		const block = readProviderFromModelsYml("anthropic", modelsPath);
		expect(block?.apiKey).toEqual({ kind: "literal", value: 'sk-"escaped"-\\key', wasQuoted: true });
	});

	it("parses a single-quoted literal apiKey verbatim (no escape decoding)", () => {
		write(
			[
				"providers:",
				"  anthropic:",
				"    baseUrl: 'https://proxy.example.com/anthropic'",
				"    apiKey: 'sk-raw-single'",
				"",
			].join("\n"),
		);

		const block = readProviderFromModelsYml("anthropic", modelsPath);
		expect(block?.baseUrl).toBe("https://proxy.example.com/anthropic");
		expect(block?.apiKey).toEqual({ kind: "literal", value: "sk-raw-single", wasQuoted: true });
	});

	it("classifies shell-backed apiKey entries without resolving them", () => {
		write(
			[
				"providers:",
				"  anthropic:",
				'    baseUrl: "https://proxy.example.com/anthropic"',
				"    apiKey: !secret get-key",
				"",
			].join("\n"),
		);

		const block = readProviderFromModelsYml("anthropic", modelsPath);
		expect(block?.apiKey?.kind).toBe("shellSecret");
	});

	it("returns null when the requested provider block is absent", () => {
		write(
			[
				"providers:",
				"  litellm:",
				'    baseUrl: "https://proxy.example.com/v1"',
				"    apiKey: LITELLM_API_KEY",
				"",
			].join("\n"),
		);

		expect(readProviderFromModelsYml("anthropic", modelsPath)).toBeNull();
	});

	it("does not leak entries from sibling provider blocks", () => {
		write(
			[
				"providers:",
				"  anthropic:",
				'    baseUrl: "https://proxy.example.com/anthropic"',
				"    apiKey: ANTHROPIC_KEY",
				"  litellm:",
				'    baseUrl: "https://proxy.example.com/v1"',
				"    apiKey: LITELLM_KEY",
				"",
			].join("\n"),
		);

		const anthropic = readProviderFromModelsYml("anthropic", modelsPath);
		expect(anthropic?.baseUrl).toBe("https://proxy.example.com/anthropic");
		expect(anthropic?.apiKey).toEqual({ kind: "envVar", name: "ANTHROPIC_KEY" });

		const litellm = readProviderFromModelsYml("litellm", modelsPath);
		expect(litellm?.baseUrl).toBe("https://proxy.example.com/v1");
		expect(litellm?.apiKey).toEqual({ kind: "envVar", name: "LITELLM_KEY" });
	});

	it("handles 4-space indentation", () => {
		write(
			[
				"providers:",
				"    anthropic:",
				'        baseUrl: "https://proxy.example.com/anthropic"',
				"        apiKey: LITELLM_API_KEY",
				"",
			].join("\n"),
		);

		const block = readProviderFromModelsYml("anthropic", modelsPath);
		expect(block?.baseUrl).toBe("https://proxy.example.com/anthropic");
		expect(block?.apiKey).toEqual({ kind: "envVar", name: "LITELLM_API_KEY" });
	});

	it("treats a bare non-env-var value as an unquoted literal", () => {
		write(
			[
				"providers:",
				"  anthropic:",
				'    baseUrl: "https://proxy.example.com/anthropic"',
				"    apiKey: sk-direct-literal",
				"",
			].join("\n"),
		);

		const block = readProviderFromModelsYml("anthropic", modelsPath);
		expect(block?.apiKey).toEqual({ kind: "literal", value: "sk-direct-literal", wasQuoted: false });
	});

	it("ignores fields outside the providers section", () => {
		write(
			[
				"providers:",
				"  anthropic:",
				'    baseUrl: "https://proxy.example.com/anthropic"',
				"    apiKey: FIRST_KEY",
				"modelRoles:",
				"  anthropic:",
				'    baseUrl: "https://should-be-ignored"',
				"    apiKey: SHOULD_BE_IGNORED",
				"",
			].join("\n"),
		);

		const block = readProviderFromModelsYml("anthropic", modelsPath);
		expect(block?.baseUrl).toBe("https://proxy.example.com/anthropic");
		expect(block?.apiKey).toEqual({ kind: "envVar", name: "FIRST_KEY" });
	});

	it("returns null when neither baseUrl nor apiKey is present", () => {
		write(["providers:", "  anthropic:", "    notes: nothing useful here", ""].join("\n"));
		expect(readProviderFromModelsYml("anthropic", modelsPath)).toBeNull();
	});

	it("classifies bare all-caps tokens without underscores as literals", () => {
		// Env-var references in this codebase (LITELLM_API_KEY, ANTHROPIC_API_KEY, …)
		// all contain at least one underscore. A short all-caps string like "SK12345"
		// almost certainly denotes a hand-edited literal, not an env var.
		write(
			[
				"providers:",
				"  anthropic:",
				'    baseUrl: "https://proxy.example.com/anthropic"',
				"    apiKey: SK12345",
				"",
			].join("\n"),
		);

		const block = readProviderFromModelsYml("anthropic", modelsPath);
		expect(block?.apiKey).toEqual({ kind: "literal", value: "SK12345", wasQuoted: false });
	});

	it("does not confuse a nested anthropic: inside another provider with the target block", () => {
		// A sub-map under a different provider that happens to contain the target
		// provider's name must not pollute the read. Only the real top-level
		// `providers.anthropic` block should be returned.
		write(
			[
				"providers:",
				"  someProvider:",
				"    anthropic:",
				'      baseUrl: "https://ignored.example.com/anthropic"',
				"      apiKey: SHOULD_NOT_LEAK",
				"  anthropic:",
				'    baseUrl: "https://correct.example.com/anthropic"',
				"    apiKey: CORRECT_KEY",
				"",
			].join("\n"),
		);

		const block = readProviderFromModelsYml("anthropic", modelsPath);
		expect(block?.baseUrl).toBe("https://correct.example.com/anthropic");
		expect(block?.apiKey).toEqual({ kind: "envVar", name: "CORRECT_KEY" });
	});

	it("ignores keys inside nested sub-maps of the target block", () => {
		// A `discovery:` sub-map (as used for the litellm provider) or any other
		// nested map must not overwrite the target block's baseUrl / apiKey even
		// if the nested map contains keys with the same name.
		write(
			[
				"providers:",
				"  anthropic:",
				'    baseUrl: "https://correct.example.com/anthropic"',
				"    apiKey: REAL_KEY",
				"    discovery:",
				'      baseUrl: "https://nested-should-not-leak"',
				"      apiKey: NESTED_SHOULD_NOT_LEAK",
				"",
			].join("\n"),
		);

		const block = readProviderFromModelsYml("anthropic", modelsPath);
		expect(block?.baseUrl).toBe("https://correct.example.com/anthropic");
		expect(block?.apiKey).toEqual({ kind: "envVar", name: "REAL_KEY" });
	});

	it("exits the target block cleanly on a sibling provider", () => {
		write(
			[
				"providers:",
				"  anthropic:",
				'    baseUrl: "https://correct.example.com/anthropic"',
				"    apiKey: CORRECT_KEY",
				"  litellm:",
				'    baseUrl: "https://correct.example.com/v1"',
				"    apiKey: LITELLM_KEY",
				"",
			].join("\n"),
		);

		const anthropic = readProviderFromModelsYml("anthropic", modelsPath);
		expect(anthropic?.baseUrl).toBe("https://correct.example.com/anthropic");
		expect(anthropic?.apiKey).toEqual({ kind: "envVar", name: "CORRECT_KEY" });
	});
});
