/**
 * Auto-configuration for LiteLLM proxy.
 *
 * When LITELLM_BASE_URL and LITELLM_API_KEY are set but no models.yml exists,
 * automatically generates working configuration so xcsh works out of the box.
 *
 * Also validates existing config against env vars and auto-fixes drift.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { $env, logger } from "@f5xc-salesdemos/pi-utils";

// ---------------------------------------------------------------------------
// Detection
// ---------------------------------------------------------------------------

/** Check if LiteLLM env vars are set and usable. */
export function hasLiteLLMEnv(): boolean {
	const baseUrl = $env.LITELLM_BASE_URL?.trim();
	const apiKey = $env.LITELLM_API_KEY?.trim();
	return !!baseUrl && !!apiKey && (baseUrl.startsWith("http://") || baseUrl.startsWith("https://"));
}

/** Get the LiteLLM base URL from env, normalized (no trailing slash). */
function getLiteLLMBaseUrl(): string | undefined {
	const raw = $env.LITELLM_BASE_URL?.trim();
	if (!raw) return undefined;
	return raw.replace(/\/+$/, "");
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

/** Generate models.yml content for LiteLLM proxy. */
export function generateModelsYml(baseUrl: string): string {
	return [
		"# Auto-generated by xcsh for LiteLLM proxy",
		"# API key resolved from LITELLM_API_KEY env var at runtime",
		"providers:",
		"  anthropic:",
		`    baseUrl: "${baseUrl}/anthropic"`,
		"    apiKey: LITELLM_API_KEY",
		"",
	].join("\n");
}

/** Generate config.yml with sensible defaults for LiteLLM. */
export function generateConfigYml(): string {
	return [
		"# Auto-generated by xcsh for LiteLLM proxy",
		"providers:",
		"  image: openai",
		"",
		"generate_image:",
		"  enabled: true",
		"",
		"inspect_image:",
		"  enabled: true",
		"",
		"images:",
		"  blockImages: false",
		"  autoResize: true",
		"",
		"terminal:",
		"  showImages: true",
		"",
	].join("\n");
}

// ---------------------------------------------------------------------------
// Auto-config on startup
// ---------------------------------------------------------------------------

/**
 * Try to auto-generate models.yml and config.yml for LiteLLM.
 * Called when models.yml is not found and LITELLM env vars are set.
 * Returns true if config was generated.
 */
export function tryAutoConfigLiteLLM(modelsPath: string): boolean {
	if (!hasLiteLLMEnv()) return false;

	const baseUrl = getLiteLLMBaseUrl();
	if (!baseUrl) return false;

	const dir = path.dirname(modelsPath);

	try {
		fs.mkdirSync(dir, { recursive: true });

		// Write models.yml
		fs.writeFileSync(modelsPath, generateModelsYml(baseUrl), "utf-8");
		logger.debug("Auto-configured LiteLLM proxy", { modelsPath, baseUrl });

		// Write config.yml if it doesn't exist
		const configPath = path.join(dir, "config.yml");
		if (!fs.existsSync(configPath)) {
			fs.writeFileSync(configPath, generateConfigYml(), "utf-8");
			logger.debug("Auto-generated default config", { configPath });
		}

		return true;
	} catch (err) {
		logger.warn("Failed to auto-generate LiteLLM config", { err, modelsPath });
		return false;
	}
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

export interface ValidationResult {
	valid: boolean;
	errors: string[];
	warnings: string[];
	fixable: boolean;
}

/**
 * Validate existing models.yml against environment.
 * Returns validation result with errors and warnings.
 */
export function validateModelsConfig(modelsPath: string): ValidationResult {
	const result: ValidationResult = { valid: true, errors: [], warnings: [], fixable: false };

	// Check file exists
	if (!fs.existsSync(modelsPath)) {
		result.valid = false;
		result.errors.push("models.yml not found");
		result.fixable = hasLiteLLMEnv();
		return result;
	}

	// Check file is readable
	let content: string;
	try {
		content = fs.readFileSync(modelsPath, "utf-8");
	} catch {
		result.valid = false;
		result.errors.push("models.yml is not readable");
		return result;
	}

	// Check YAML syntax
	try {
		// Basic content check — full schema validation is done by ConfigFile loader
		if (content.trim().length === 0) {
			result.valid = false;
			result.errors.push("models.yml is empty");
			result.fixable = hasLiteLLMEnv();
			return result;
		}
	} catch {
		result.valid = false;
		result.errors.push("models.yml has invalid YAML syntax");
		result.fixable = hasLiteLLMEnv();
		return result;
	}

	// Check env var alignment
	const envBaseUrl = getLiteLLMBaseUrl();
	if (envBaseUrl) {
		const expectedAnthropicUrl = `${envBaseUrl}/anthropic`;
		if (!content.includes(expectedAnthropicUrl)) {
			result.warnings.push(
				`Anthropic baseUrl in models.yml does not match LITELLM_BASE_URL. Expected: ${expectedAnthropicUrl}`,
			);
			result.fixable = true;
		}
	}

	// Check apiKey references a set env var
	if (content.includes("apiKey: LITELLM_API_KEY") && !$env.LITELLM_API_KEY) {
		result.warnings.push("models.yml references LITELLM_API_KEY but the env var is not set");
	}

	return result;
}

// ---------------------------------------------------------------------------
// Auto-fix
// ---------------------------------------------------------------------------

export interface FixResult {
	fixed: boolean;
	changes: string[];
}

/**
 * Auto-fix models.yml issues.
 * Regenerates the file if LITELLM env vars are set.
 */
export function autoFixModelsConfig(modelsPath: string): FixResult {
	if (!hasLiteLLMEnv()) {
		return { fixed: false, changes: ["Cannot fix: LITELLM_BASE_URL or LITELLM_API_KEY not set"] };
	}

	const baseUrl = getLiteLLMBaseUrl();
	if (!baseUrl) {
		return { fixed: false, changes: ["Cannot fix: LITELLM_BASE_URL is invalid"] };
	}

	try {
		const dir = path.dirname(modelsPath);
		fs.mkdirSync(dir, { recursive: true });

		// Back up existing file if it exists
		if (fs.existsSync(modelsPath)) {
			const backupPath = `${modelsPath}.bak`;
			fs.copyFileSync(modelsPath, backupPath);
		}

		fs.writeFileSync(modelsPath, generateModelsYml(baseUrl), "utf-8");
		logger.debug("Auto-fixed LiteLLM config", { modelsPath, baseUrl });

		return { fixed: true, changes: [`Regenerated models.yml with baseUrl: ${baseUrl}/anthropic`] };
	} catch (err) {
		logger.warn("Failed to auto-fix LiteLLM config", { err, modelsPath });
		return { fixed: false, changes: [`Write failed: ${err}`] };
	}
}

/**
 * Validate config against env and warn if drifted.
 * Called on every startup when models.yml exists and loads successfully.
 */
export function warnIfConfigDrifted(providers: Record<string, { baseUrl?: string }> | undefined): void {
	if (!providers) return;

	const envBaseUrl = getLiteLLMBaseUrl();
	if (!envBaseUrl) return;

	const anthropicConfig = providers.anthropic;
	if (!anthropicConfig?.baseUrl) return;

	const expectedUrl = `${envBaseUrl}/anthropic`;
	if (anthropicConfig.baseUrl !== expectedUrl) {
		logger.warn("LiteLLM config drift detected", {
			configured: anthropicConfig.baseUrl,
			expected: expectedUrl,
			hint: "Run 'xcsh setup litellm --force' to update",
		});
	}
}
