/**
 * Auto-configuration and self-healing for LiteLLM proxy.
 *
 * Runs on every startup to ensure xcsh has a working configuration:
 *
 * 1. Missing config → auto-generate from LITELLM env vars
 * 2. Corrupt config → backup and regenerate
 * 3. Empty config → regenerate
 * 4. Drifted config → detect and auto-fix (URL changed in env)
 * 5. Incomplete config → fill missing fields
 * 6. Outdated config → detect missing/old configVersion, backup and regenerate
 *
 * All fixes create .bak backups before overwriting.
 * All operations are idempotent and safe to run repeatedly.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { $env, logger } from "@f5xc-salesdemos/pi-utils";

/** Current config schema version. Bump when the generated format changes. */
export const CURRENT_CONFIG_VERSION = 1;

// ---------------------------------------------------------------------------
// Detection
// ---------------------------------------------------------------------------

/** Check if LiteLLM env vars are set and usable. */
export function hasLiteLLMEnv(): boolean {
	const baseUrl = $env.LITELLM_BASE_URL?.trim();
	const apiKey = $env.LITELLM_API_KEY?.trim();
	return !!baseUrl && !!apiKey && (baseUrl.startsWith("http://") || baseUrl.startsWith("https://"));
}

/** Get the LiteLLM base URL from env, normalized (no trailing slash). */
function getLiteLLMBaseUrl(): string | undefined {
	const raw = $env.LITELLM_BASE_URL?.trim();
	if (!raw) return undefined;
	return raw.replace(/\/+$/, "");
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

/** Generate models.yml content for LiteLLM proxy. */
export function generateModelsYml(baseUrl: string): string {
	return [
		"# Auto-generated by xcsh for LiteLLM proxy",
		"# API key resolved from LITELLM_API_KEY env var at runtime",
		`configVersion: ${CURRENT_CONFIG_VERSION}`,
		"providers:",
		"  anthropic:",
		`    baseUrl: "${baseUrl}/anthropic"`,
		"    apiKey: LITELLM_API_KEY",
		"",
	].join("\n");
}

/** Generate config.yml with sensible defaults for LiteLLM. */
export function generateConfigYml(): string {
	return [
		"# Auto-generated by xcsh for LiteLLM proxy",
		"providers:",
		"  image: openai",
		"",
		"generate_image:",
		"  enabled: true",
		"",
		"inspect_image:",
		"  enabled: true",
		"",
		"images:",
		"  blockImages: false",
		"  autoResize: true",
		"",
		"terminal:",
		"  showImages: true",
		"",
	].join("\n");
}

// ---------------------------------------------------------------------------
// Backup
// ---------------------------------------------------------------------------

/** Create a .bak backup of a file if it exists. Returns true if backed up. */
function backupIfExists(filePath: string): boolean {
	try {
		if (fs.existsSync(filePath)) {
			fs.copyFileSync(filePath, `${filePath}.bak`);
			return true;
		}
	} catch (err) {
		logger.warn("Failed to create backup", { filePath, err });
	}
	return false;
}

/** Safely write a file, creating parent directories. */
function safeWrite(filePath: string, content: string): boolean {
	try {
		fs.mkdirSync(path.dirname(filePath), { recursive: true });
		fs.writeFileSync(filePath, content, "utf-8");
		return true;
	} catch (err) {
		logger.warn("Failed to write config file", { filePath, err });
		return false;
	}
}

// ---------------------------------------------------------------------------
// Auto-config on startup (handles missing file)
// ---------------------------------------------------------------------------

/**
 * Try to auto-generate models.yml and config.yml for LiteLLM.
 * Called when models.yml is not found and LITELLM env vars are set.
 * Returns true if config was generated.
 */
export function tryAutoConfigLiteLLM(modelsPath: string): boolean {
	if (!hasLiteLLMEnv()) return false;

	const baseUrl = getLiteLLMBaseUrl();
	if (!baseUrl) return false;

	if (!safeWrite(modelsPath, generateModelsYml(baseUrl))) return false;
	logger.debug("Auto-configured LiteLLM proxy", { modelsPath, baseUrl });

	// Write config.yml if it doesn't exist
	const configPath = path.join(path.dirname(modelsPath), "config.yml");
	if (!fs.existsSync(configPath)) {
		safeWrite(configPath, generateConfigYml());
		logger.debug("Auto-generated default config", { configPath });
	}

	return true;
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

export interface ValidationResult {
	valid: boolean;
	errors: string[];
	warnings: string[];
	fixable: boolean;
}

/**
 * Validate existing models.yml against environment.
 *
 * Checks:
 * - File exists and is readable
 * - File is not empty or whitespace-only
 * - Contains expected providers section
 * - configVersion matches CURRENT_CONFIG_VERSION
 * - Anthropic baseUrl matches LITELLM_BASE_URL env var
 * - apiKey env var reference resolves to a set variable
 */
export function validateModelsConfig(modelsPath: string): ValidationResult {
	const result: ValidationResult = { valid: true, errors: [], warnings: [], fixable: false };

	// Check file exists
	if (!fs.existsSync(modelsPath)) {
		result.valid = false;
		result.errors.push("models.yml not found");
		result.fixable = hasLiteLLMEnv();
		return result;
	}

	// Check file is readable
	let content: string;
	try {
		content = fs.readFileSync(modelsPath, "utf-8");
	} catch {
		result.valid = false;
		result.errors.push("models.yml is not readable");
		return result;
	}

	// Check not empty
	if (content.trim().length === 0) {
		result.valid = false;
		result.errors.push("models.yml is empty");
		result.fixable = hasLiteLLMEnv();
		return result;
	}

	// Check for providers section (basic structural check)
	if (!content.includes("providers:")) {
		result.valid = false;
		result.errors.push("models.yml missing 'providers:' section");
		result.fixable = hasLiteLLMEnv();
		return result;
	}

	// Check config version
	if (!content.includes(`configVersion: ${CURRENT_CONFIG_VERSION}`)) {
		result.warnings.push(
			`models.yml missing or outdated configVersion (expected ${CURRENT_CONFIG_VERSION}). Run 'xcsh setup litellm' to upgrade.`,
		);
		result.fixable = true;
	}

	// Check env var alignment
	const envBaseUrl = getLiteLLMBaseUrl();
	if (envBaseUrl) {
		const expectedAnthropicUrl = `${envBaseUrl}/anthropic`;
		if (!content.includes(expectedAnthropicUrl)) {
			result.warnings.push(
				`Anthropic baseUrl in models.yml does not match LITELLM_BASE_URL. Expected: ${expectedAnthropicUrl}`,
			);
			result.fixable = true;
		}
	}

	// Check apiKey references a set env var
	if (content.includes("apiKey: LITELLM_API_KEY") && !$env.LITELLM_API_KEY) {
		result.warnings.push("models.yml references LITELLM_API_KEY but the env var is not set");
	}

	return result;
}

// ---------------------------------------------------------------------------
// Auto-fix (handles corrupt, drifted, incomplete configs)
// ---------------------------------------------------------------------------

export interface FixResult {
	fixed: boolean;
	changes: string[];
}

/**
 * Auto-fix models.yml issues.
 *
 * Handles:
 * - Corrupt YAML → backup and regenerate
 * - Empty file → regenerate
 * - URL drift → backup and regenerate with new URL
 * - Missing providers section → regenerate
 *
 * Always creates .bak backup before overwriting.
 */
export function autoFixModelsConfig(modelsPath: string): FixResult {
	if (!hasLiteLLMEnv()) {
		return { fixed: false, changes: ["Cannot fix: LITELLM_BASE_URL or LITELLM_API_KEY not set"] };
	}

	const baseUrl = getLiteLLMBaseUrl();
	if (!baseUrl) {
		return { fixed: false, changes: ["Cannot fix: LITELLM_BASE_URL is invalid"] };
	}

	backupIfExists(modelsPath);

	if (!safeWrite(modelsPath, generateModelsYml(baseUrl))) {
		return { fixed: false, changes: [`Write failed: could not write to ${modelsPath}`] };
	}

	logger.debug("Auto-fixed LiteLLM config", { modelsPath, baseUrl });
	return { fixed: true, changes: [`Regenerated models.yml with baseUrl: ${baseUrl}/anthropic`] };
}

// ---------------------------------------------------------------------------
// Startup self-healing (called from ModelRegistry on every load)
// ---------------------------------------------------------------------------

/**
 * Comprehensive startup health check for models.yml.
 *
 * Called from ModelRegistry.#loadCustomModels() on every startup.
 * Handles all error conditions:
 *
 * - "not-found" → tryAutoConfigLiteLLM (generate from env)
 * - "error" (corrupt/invalid) → autoFixModelsConfig (backup + regenerate)
 * - "ok" but drifted → autoFixModelsConfig (backup + update URL)
 * - "ok" but outdated configVersion → autoFixModelsConfig (backup + upgrade)
 *
 * Returns true if any repair was performed (caller should invalidate cache and reload).
 */
export function startupHealthCheck(
	status: "ok" | "not-found" | "error",
	modelsPath: string,
	loadedProviders?: Record<string, { baseUrl?: string }>,
): boolean {
	// Case 1: No config file — generate from env
	if (status === "not-found") {
		return tryAutoConfigLiteLLM(modelsPath);
	}

	// Case 2: Config file exists but failed to parse — backup and regenerate
	if (status === "error") {
		if (!hasLiteLLMEnv()) return false;
		const fix = autoFixModelsConfig(modelsPath);
		return fix.fixed;
	}

	// Case 3: Config loaded OK — check for drift and auto-fix
	if (status === "ok" && loadedProviders) {
		const envBaseUrl = getLiteLLMBaseUrl();
		if (!envBaseUrl) return false;

		const anthropicConfig = loadedProviders.anthropic;
		if (!anthropicConfig?.baseUrl) return false;

		const expectedUrl = `${envBaseUrl}/anthropic`;
		if (anthropicConfig.baseUrl !== expectedUrl) {
			logger.warn("LiteLLM config drift detected — auto-fixing", {
				configured: anthropicConfig.baseUrl,
				expected: expectedUrl,
			});
			const fix = autoFixModelsConfig(modelsPath);
			return fix.fixed;
		}

		// Case 4: Config OK and URL matches, but configVersion is missing or outdated
		try {
			const content = fs.readFileSync(modelsPath, "utf-8");
			if (!content.includes(`configVersion: ${CURRENT_CONFIG_VERSION}`)) {
				logger.debug("Upgrading models.yml to configVersion", { version: CURRENT_CONFIG_VERSION });
				const fix = autoFixModelsConfig(modelsPath);
				return fix.fixed;
			}
		} catch {
			// File read failed — skip version check, don't block startup
		}
	}

	return false;
}

/**
 * Validate config against env and warn if drifted.
 * Informational only — does not fix. Use startupHealthCheck for auto-fix.
 */
export function warnIfConfigDrifted(providers: Record<string, { baseUrl?: string }> | undefined): void {
	if (!providers) return;

	const envBaseUrl = getLiteLLMBaseUrl();
	if (!envBaseUrl) return;

	const anthropicConfig = providers.anthropic;
	if (!anthropicConfig?.baseUrl) return;

	const expectedUrl = `${envBaseUrl}/anthropic`;
	if (anthropicConfig.baseUrl !== expectedUrl) {
		logger.warn("LiteLLM config drift detected", {
			configured: anthropicConfig.baseUrl,
			expected: expectedUrl,
			hint: "Run 'xcsh setup litellm' to update",
		});
	}
}
